# Copyright (c) 2023 Bitcoin Association Distributed under the Open BSV
# software license, see the accompanying file LICENSE

name: Main
run-name:

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  autotools:
    strategy:
      matrix:
        os: [ubuntu]
        version: [22.04]
        toolset: [gcc]
        toolset_version: [10]
    runs-on: [ self-hosted ]
    container:
      image: "${{ matrix.os }}:${{ matrix.version }}"
    timeout-minutes: 60
    steps:
      - name: Checkout
        if: github.event_name != 'repository_dispatch'
        uses: actions/checkout@v3
        with:
          clean: ''
      - name: Checkout branch
        if: github.event_name == 'repository_dispatch'
        uses: actions/checkout@v3
        with:
          clean: ''
          ref: ${{ github.event.client_payload.branch }}
      - name: Install build tools
        uses: ./.github/workflows/install_build_tools
        with: 
          toolset: "${{ matrix.toolset }}"
          toolset_version: "${{ matrix.toolset_version }}"
      - name: Install pre-req for bitcoin
        uses: ./.github/workflows/install_prerequisites_bitcoin
      - name: Install pre-req for autotools
        uses: ./.github/workflows/install_prerequisites_autotools
      - name: Build
        uses: ./.github/workflows/build_bitcoin_autotools
      - name: Unit test
        uses: ./.github/workflows/unit_test_bitcoin_autotools
      - name: Install pre-req for functional tests
        uses: ./.github/workflows/install_prerequisites_func_tests
      - name: Functional test
        uses: ./.github/workflows/functional_test
        
  cmake:
    strategy:
      matrix:
        os: [ubuntu]
        version : [22.04]
        toolset: [clang]
        toolset_version: [ 14, 15 ]
        build_type: [ Release, Debug ]
        include:
          - toolset_version: 15
            build_type: Release
            sanitizers: asan usan
    runs-on: [ self-hosted ]
    container:
      image: "${{ matrix.os }}:${{ matrix.version }}"
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: ''
      - name: Install build tools
        uses: ./.github/workflows/install_build_tools
        with: 
          toolset: "${{ matrix.toolset }}"
          toolset_version: "${{ matrix.toolset_version }}"
      - name: Install pre-req for bitcoin
        uses: ./.github/workflows/install_prerequisites_bitcoin
      - name: Install pre-req for cmake build
        uses: ./.github/workflows/install_prerequisites_cmake
      - name: Build Bitcoin
        uses: ./.github/workflows/build_bitcoin_cmake
        with: 
          build_type: ${{ matrix.build_type }}
          sanitizers: ${{ matrix.sanitizers }}
      - name: Unit test secp256k1
        uses: ./.github/workflows/unit_test_secp256k1_cmake
      - name: Unit test Bitcoin
        uses: ./.github/workflows/unit_test_bitcoin_cmake
      - name: Bench test Bitcoin
        uses: ./.github/workflows/bench_test_bitcoin_cmake
      - name: Install pre-req for functional tests
        uses: ./.github/workflows/install_prerequisites_func_tests
      - name: Functional test
        if: ${{ matrix.build_type != 'Debug' }}
        uses: ./.github/workflows/functional_test

